#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: PSG1218
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
        sed -i 'CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        sed -i 'CONFIG_FIRMWARE_INCLUDE_CADDY/d' .config #删除配置项在线文件管理服务
        sed -i 'CONFIG_FIRMWARE_INCLUDE_CADDYBIN/d' .config #删除配置项CADDYBIN
        sed -i 'CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config  #删除配置项ADGUARDHOME
        sed -i 'CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config  #删除配置项SRELAY
        sed -i 'CONFIG_FIRMWARE_INCLUDE_WYY/d' .config  #删除配置项WYY
        sed -i 'CONFIG_FIRMWARE_INCLUDE_WYYBIN/d' .config  #删除配置项WYYBIN
        sed -i 'CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config #zerotier ~1.3M  #删除配置项ZEROTIER
        sed -i 'CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config  #删除配置项TROJAN
        sed -i 'CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #SCUTCLIENT  #删除配置项SCUTCLIENT
        sed -i 'CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #SS plus+  #删除配置项SHADOWSOCKS
        sed -i 'CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config # simple-obfs混淆插件  #删除配置项SSOBFS
        sed -i 'CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #SS server  #删除配置项SSSERVER
        sed -i 'CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #DNSFORWARDER  #删除配置项DNSFORWARDER
        sed -i 'CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+  
        sed -i 'CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config  #删除配置项TUNSAFE 
        sed -i 'CONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config  #删除配置项V2RAY
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config  
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config  
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> .config #内网穿透FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=y" >> .config #内网穿透FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #阿里DDNS
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config #smartdns二进制文件
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=y" >> .config #KP广告过滤
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
